#!/usr/bin/env node
(function () {

    var collect = require("./index.js").collect,
        argv,    // The optimist module.
        fs,      // The fs module.
        output,  // The output file.
        path,    // The collect path.
        ignore,  // The ignore list by comma.
        modules; // The output config.

    fs = require("fs");

    // Define command-line options.
    argv = require("optimist")
        .usage("YUI Config Collector\n\n" +
            "The purpose of this script is to collect module settings " +
            "of customized YUI module files.\nBy doing this, we don't " +
            "have to maintain a centralized module dependencies config.\n\n" +
            "Usage: ycc <Search Path> --ignore " +
            "[Ignore keyword list] --output [Output File]")
        .describe("ignore", "You can ignore files by providing keyword list " +
             "which separate by common")
        .describe("output", "Output the result to a file.")
        .check(function (o) {
            if (!o._[0]) { // The path must exist.
                throw new Error("You must at least provide path.");
            }
            if (!require("fs").existsSync(o._[0])) {
                throw new Error("The path you provide doesn't exist.");
            }
        })
        .argv;

    path   = argv._[0];
    ignore = argv.ignore || null;
    ignore = (ignore) ? ignore.split(",") : null;
    output = argv.output;

    collect(path, ignore, function (modules) {
        modules = JSON.stringify(modules, null, 4);
        if (output) {
            fs.writeFileSync(output, modules);
        } else {
            console.log(modules);
        }
    });

}());
